# Generated by Django 5.0 on 2024-01-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/img')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_keyword', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('post_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.postcategory')),
            ],
        ),
    ]
